### ISSUE TITLE
Ubuntu 14.04 doesn't "make install"

### ISSUE THREAD

**Issue by Sinozet** [daringer/asus-fan#11]
cp asus_fan.ko "/usr/lib/modules/3.13.0-46-generic/"
error: there is no "/usr/lib/modules/3.13.0-46-generic/"

**Comment by daringer** [comment]
an pretty obvious bug, quick to fix, is done, just pull from github and try again---although still very rudimentary, I guess it will work on ubuntu...

**Comment by Sinozet** [comment]
Solved, thanx for help.
