### ISSUE TITLE
Support for Asus TP300L

### ISSUE THREAD

**Issue by c64bob** [daringer/asus-fan#2]
Would it be possible to add support for the asus TP300L notebook? What information would you need to implement it?

I have compiled your module on this notebook, but when I run `modprobe asus_fan` it says:

`modprobe: ERROR: could not insert 'asus_fan': No such device`

Thanks!

**Comment by daringer** [comment]
c64bob, any news on this ? did you already try the "new" (hwmon-based) module version ? If not I'll close this issue I would ask you to open a new one, once you have something new to discuss/add/contribute...

**Comment by c64bob** [comment]
Hi, I did manage to get it to work, although I found that the default fan control settings actually worked best anyway. If I tried to reduce the fan usage, then my CPU would get a lot hotter really quickly. So yeah, this issue can be closed, and thanks again for your help.

**Comment by daringer** [comment]
Could you verify that the module works with model:  "TP300L" one or two fans? was this the exact string you added? So I could add it to "supported" ...
