### ISSUE TITLE
ux32vd

### ISSUE THREAD

**Issue by Tohtar** [daringer/asus-fan#33]
why not run on the maximum fan speed(7000 RPM)?
asus_fan-isa-0000
Adapter: ISA adapter
CPU Fan:     7384 RPM  (min =   10 RPM)
GFX Fan:     7235 RPM  (min =   10 RPM)

**Comment by daringer** [comment]
max is not set by using RPM but a integer 0-255, nevertheless feel free to improve this somehow...
