### ISSUE TITLE
asus-fan.service incorrectly configured

### ISSUE THREAD

**Issue by hexadecagram** [daringer/asus-fan#36]
The line `Before=thermald.service` needs to be moved from the [Install] section to the [Unit] section.

**Comment by frederickjh** [comment]
Which file are you referring to?

**Comment by daringer** [comment]
The .service file for systemd... done
This could fix some issues with the module not being loaded before thermald is started, let's see if this is the case...

**Comment by hexadecagram** [comment]
Yes, that's the one. Sorry, this one slipped off my radar.
