### ISSUE TITLE
[UNSUPPORTED HARDWARE:  UX360UAK] - Can't run make

### ISSUE THREAD

**Issue by jonnyteronni** [daringer/asus-fan#49]
Trying to get this working on a UX360UAK:

$ make
make -C /lib/modules/4.11.3-1-ARCH/build M=$PWD modules
make[1]: Entering directory '/usr/lib/modules/4.11.3-1-ARCH/build'
make[1]: *** No rule to make target 'modules'.  Stop.
make[1]: Leaving directory '/usr/lib/modules/4.11.3-1-ARCH/build'
make: *** [Makefile:14: all] Error 2

System: 
System:    Host: JT-UX360U Kernel: 4.11.3-1-ARCH x86_64 (64 bit gcc: 7.1.1) Desktop: Gnome 3.24.2 (Gtk 3.22.15)
           Distro: Arch Linux
Machine:   Device: un-determined System: ASUSTeK product: UX360UAK v: 1.0
           Mobo: ASUSTeK model: UX360UAK v: 1.0 UEFI: American Megatrends v: UX360UAK.307 date: 03/07/2017
Battery    BAT0: charge: 16.4 Wh 28.6% condition: 57.4/57.1 Wh (101%) model: ASUSTeK ASUS status: Discharging
CPU:       Dual core Intel Core i7-7500U (-HT-MCP-) cache: 4096 KB
           flags: (lm nx sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx) bmips: 11620
           clock speeds: max: 3500 MHz 1: 699 MHz 2: 699 MHz 3: 699 MHz 4: 699 MHz
Graphics:  Card: Intel Device 5916 bus-ID: 00:02.0
           Display Server: X.Org 1.19.3 drivers: intel (unloaded: modesetting,fbdev,vesa)
           Resolution: 1920x1080@60.00hz
           GLX Renderer: Mesa DRI Intel HD Graphics 620 (Kaby Lake GT2)
           GLX Version: 3.0 Mesa 17.1.0 Direct Rendering: Yes
Audio:     Card Intel Device 9d71 driver: snd_hda_intel bus-ID: 00:1f.3 Sound: ALSA v: k4.11.3-1-ARCH
Network:   Card: Intel Wireless 8260 driver: iwlwifi bus-ID: 02:00.0
           IF: wlp2s0 state: up mac: <filter>
Drives:    HDD Total Size: 512.1GB (10.5% used)
           ID-1: /dev/sda model: Micron_1100_MTFD size: 512.1GB
Partition: ID-1: / size: 29G used: 9.4G (35%) fs: ext4 dev: /dev/dm-0
           ID-2: /boot size: 240M used: 59M (27%) fs: ext4 dev: /dev/sda2
           ID-3: /home size: 432G used: 34G (9%) fs: ext4 dev: /dev/dm-2
           ID-4: swap-1 size: 8.25GB used: 0.00GB (0%) fs: swap dev: /dev/dm-1
Sensors:   System Temperatures: cpu: 35.5C mobo: N/A
           Fan Speeds (in rpm): cpu: N/A
Info:      Processes: 222 Uptime: 2 days Memory: 5140.6/7873.5MB Init: systemd Gcc sys: 7.1.1
           Client: Shell (bash 4.4.121) inxi: 2.3.9

**Comment by afilipovich** [comment]
I guess "make" does not work for you because of non-default Makfile name.

PKGBUILD runs make as "make -f Makefile.dkms"

**Comment by daringer** [comment]
Weeeird, especially on Arch this should work without issues, just `make` shall use the kernel headers from the `/lib/modules/<kernelversion>/build` and build the module. As far as I know I suppose there are the following possibilities that this fails:
- you just ran `pacman -Syu` or updated your kernel, thus `uname -a` points to the still running kernel, but its sources are already cleaned up---means not existing anymore
- the "linux-headers" package is not installed? (is this even possible)

For me running `make` looks like this:
```bash
|-$ make
make -C /lib/modules/4.11.2-1-ARCH/build M=$PWD modules
make[1]: Entering directory '/usr/lib/modules/4.11.2-1-ARCH/build'
  CC [M]  /home/<user>/dev/asus-fan/asus_fan.o
  Building modules, stage 2.
  MODPOST 1 modules
  CC      /home/<user>/dev/asus-fan/asus_fan.mod.o
  LD [M]  /home/<user>/dev/asus-fan/asus_fan.ko
make[1]: Leaving directory '/usr/lib/modules/4.11.2-1-ARCH/build'
```

**Comment by daringer** [comment]
seems to be stalled or resolved, please feel free to re-open if issue still exists...
