### ISSUE TITLE
System hangs on suspend/reboot/poweroff

### ISSUE THREAD

**Issue by mmatuska** [daringer/asus-fan#58]
My ASUS UX32L hangs when asus_fan is loaded and I am trying to suspend, reboot or poweroff. How can I help debug this issue? I am using fancontrol.

**Comment by mmatuska** [comment]
Now I know more - the issue happens when my sensors applet periodically reads the asus_fan sensors. After switching to other sensors suspend/reboot/poweroff works again.

**Comment by daringer** [comment]
weird anyways, how reading might hang the system.
sounds like asus_fan is not properly handling unloading/suspending?
