### ISSUE TITLE
Symlink script not working on archlinux

### ISSUE THREAD

**Issue by savisitor15** [daringer/asus-fan#67]
While creating the symlinks
the fan_cpu_speed link isn't made. This is due to the check not being dynamic like the gfx check.
in file: asus-fan-create-symlinks.sh
```bash
# fan interface
[ -r /pwm1 ] && \
        ln -s ${hwmon_dir}/pwm1 ${d}/fan_cpu_speed
```
should be:
```bash
# fan interface
[ -r ${hwmon_dir}/pwm1 ] && \
        ln -s ${hwmon_dir}/pwm1 ${d}/fan_cpu_speed
```

**Comment by daringer** [comment]
ooops, nice finding thank you, fixed...
