### ISSUE TITLE
.INSTALL: line 11: systemctl: command not found

### ISSUE THREAD

**Issue by zorbanaut** [daringer/asus-fan#74]
When installing from AUR:

```
Enabling asus-fan as service in systemd
/tmp/alpm_oXXUVV/.INSTALL: line 11: systemctl: command not found
error: command failed to execute correctly
```

Commenting out that line in asus-fan-dkms-git.install helped.

**Comment by daringer** [comment]
this weird, as `systemctl` should indeed exist, maybe the full path would help, trying a non-tested fix in a minute

**Comment by daringer** [comment]
could you maybe re-run and report if it's working now?

**Comment by zorbanaut** [comment]
Sorry, I was not clear about my environment. I don't have systemctl installed.
Is it possible to add a condition to skip this step when systemctl is not available?

**Comment by daringer** [comment]
no problem, please try again now, should just warn and continue...

**Comment by zorbanaut** [comment]
Thanks for the fix, it works for me now.

"xsystemctl" is a typo?

**Comment by daringer** [comment]
kind off, intended debug-typo, thanks for pointing it out, hopefully now correct, 
closing here, don't hesitate to reopen if needed
